version: '3.7'

services:
  
  hhs-service-identity:
    build:
      context: ../
      dockerfile: src/Hhs.IdentityService.Http.Host/Dockerfile
    container_name: hhs-service-identity_container
    image: hhs-service-identity_image:latest
    restart: always
    ports:
      - "7410:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
      - infra-network

networks:
  infra-network:
    name: local.infrastructure-network
    external: true