version: '3.7'

services:
  
  hhs-service-identity:
    build:
      context: ../
      dockerfile: src/Hhs.IdentityService.Http.Host/Dockerfile
    container_name: hhs-service-identity_container
    image: hhs-service-identity_image:latest
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "7410:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=stage
    networks:
      - infra-network

networks:
  infra-network:
    name: local.infrastructure-network
    external: true